export const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION';
export const CHANGE_PLAN = 'CHANGE_PLAN';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const EDIT_BILLING = 'EDIT_BILLING';
export const REACTIVATE_SUBSCRIPTION = 'REACTIVATE_SUBSCRIPTION';